FORTUNES = [
    # Life and Personal Growth
    "A journey of a thousand miles begins with a single crab step.",
    "Your shell may be hard, but your heart is golden.",
    "Like the changing tides, positive change is coming to your life.",
    "The ocean of opportunity is vast - dive in!",
    "Your patience will be rewarded with pearls of wisdom.",
    "Trust your instincts - they're as sharp as a crab's claw.",
    "A smile is your umbrella on life's rainy beach days.",
    "Your true strength lies in your adaptability, like a tide pool creature.",
    "The best sand castles are built one grain at a time.",
    "Your creative waves will make a splash in the world.",

    # Relationships and Love
    "Love will wash up on your shore when you least expect it.",
    "A deep friendship will surface like a beautiful shell.",
    "Your heart's tide is turning towards something wonderful.",
    "Someone special will share your beach blanket of life.",
    "A strong partnership will weather any storm.",
    "Like two starfish in a tide pool, you'll find your perfect match.",
    "Your kindness to others will return like the tide.",
    "A new friendship will shine like sea glass in the sun.",
    "Family bonds will grow stronger than a hermit crab's grip.",
    "Your compassion will create ripples of joy for others.",

    # Career and Success
    "Your career will soar like a seagull catching the wind.",
    "Success awaits in unexpected tide pools.",
    "A golden opportunity will wash up on your shore.",
    "Your hard work will bear fruit like a coral reef.",
    "Leadership skills will emerge like a lighthouse in the fog.",
    "Financial tides are turning in your favor.",
    "Your talents will shine like the sun on the water.",
    "A new venture will prove as vast as the ocean.",
    "Professional growth is on the horizon, vast as the sea.",
    "Your dedication will create waves of success.",

    # Adventure and Travel
    "An exciting journey across the seas awaits you.",
    "Adventure calls from distant shores.",
    "New horizons will expand your world view.",
    "A tropical paradise will welcome you soon.",
    "Travel plans will flow smoothly like calm waters.",
    "An unexpected detour will lead to treasure.",
    "Your path will cross with fellow adventurers.",
    "A voyage of discovery is about to begin.",
    "Foreign shores will bring new perspectives.",
    "The winds of adventure are filling your sails.",

    # Wisdom and Knowledge
    "Ancient ocean wisdom will guide your path.",
    "Knowledge will flow like endless waves.",
    "Your mind will expand like the vast horizon.",
    "Wisdom comes in waves - ride them well.",
    "Learning opportunities will surface everywhere.",
    "Your curiosity will uncover hidden treasures.",
    "Understanding will dawn like the sun over water.",
    "New skills will emerge from the depths.",
    "Knowledge sought is wisdom found.",
    "Your questions will lead to pearl-like answers.",

    # Fortune and Luck
    "Good fortune rides the next wave in.",
    "Lucky stars will align like shells on the shore.",
    "A surprise blessing approaches with the tide.",
    "Fortune favors the brave-hearted crab.",
    "Your lucky shell brings double happiness.",
    "Prosperity flows like the endless tide.",
    "Good luck swims in your direction.",
    "A streak of fortune brightens your horizon.",
    "Lucky circumstances align in your favor.",
    "Fortune smiles upon your endeavors.",

    # Health and Wellness
    "Your energy will flow like ocean currents.",
    "Wellness washes over you like gentle waves.",
    "Health and vitality surge through your days.",
    "Your spirit will shine like morning sun on water.",
    "Balance finds you like a perfectly poised shell.",
    "Healing comes with the changing tide.",
    "Strength builds like waves on the shore.",
    "Vitality fills you like the ocean breeze.",
    "Your health flourishes like seaside flowers.",
    "Peace flows through you like calm waters.",

    # Creativity and Inspiration
    "Inspiration strikes like lightning over water.",
    "Your creativity flows like endless waves.",
    "Artistic ventures bloom like coral gardens.",
    "New ideas surface like dolphins at play.",
    "Your imagination spans ocean depths.",
    "Creative projects shine like sea stars.",
    "Inspiration finds you by the shore.",
    "Your artistic spirit soars like coastal birds.",
    "Original thoughts bubble up like springs.",
    "Creative success sparkles like sun on water.",

    # Personal Power
    "Your influence spreads like ripples on water.",
    "Inner strength builds like ocean currents.",
    "Personal power flows through your actions.",
    "Leadership emerges like the morning sun.",
    "Your confidence grows like rising tides.",
    "Strength shows in quiet moments.",
    "Personal growth leads to greater heights.",
    "Your potential knows no bounds.",
    "Inner wisdom guides your choices.",
    "Success comes naturally to you.",

    # Future and Change
    "Change brings renewal like ocean tides.",
    "Your future brightens like dawn over water.",
    "New beginnings wash in with the tide.",
    "Positive changes approach like gentle waves.",
    "Tomorrow brings treasures to your shore.",
    "Fresh starts lead to amazing discoveries.",
    "Your path ahead clears like morning mist.",
    "Future success builds like gathering waves.",
    "Changes bring unexpected blessings.",
    "Your destiny unfolds like a perfect shell."
] 